---
- name: Create StatefulSet for Memcache
  k8s:
    definition: "{{ lookup('template', 'memcache_statefulset.yaml.j2')|from_yaml }}"

- name: Create Service for Memcache
  k8s:
    definition: "{{ lookup('template', 'memcache_service.yaml.j2')|from_yaml }}"

- name: Create Deployment for Mcrouter attaching memcache servers to its pool
  k8s:
    definition: "{{ lookup('template', 'mcrouter_deployment.yaml.j2')|from_yaml }}"
